fail_fast: false
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
      - id: clang-tidy
      - id: cpplint
        args: [--linelength=100, '--filter=-legal/copyright,-runtime/reference']
