cc_library(
    name = "is_number",
    testonly = 1,
    srcs = ["is_number.cc"],
    hdrs = ["is_number.h"],
    include_prefix = "xdk/lua/matchers",
    visibility = ["//:__pkg__"],
    deps = [
        "//:stack",
        "@com_google_googletest//:gtest",
    ],
)

cc_library(
    name = "element",
    testonly = 1,
    srcs = ["element.cc"],
    hdrs = ["element.h"],
    include_prefix = "xdk/lua/matchers",
    visibility = ["//:__pkg__"],
    deps = [
        "//:stack",
        "@com_google_googletest//:gtest",
    ],
)
